# -*- coding: utf-8 -*-
"""Simple Sentiment Text Analysis in Python

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1VGPUdG4Lkf8jLikiLeXC_FYinEi-nNX2
"""

#Simple Sentiment Text Analysis in Python

!pip install nltk

!pip install textblob

!pip install newspaper3k

from textblob import TextBlob
from newspaper import Article

import nltk
nltk.download('punkt')

# Vamos usar um texto supostamente neutro

url = 'https://pt.wikipedia.org/wiki/Matem%C3%A1tica'

article = Article(url)

# Pegando algumas informações do artigo:

article.download()
article.parse()
article.nlp()

# Compilando as informações em texto do site

text = article.text
print(text)

# Agora que temos todo o texto, vamos criar um objeto text blob dele:

translation = TextBlob(text)
pt_blob = translation.translate(from_lang='pt', to='en')
blob = TextBlob(text)
sentiment = blob.sentiment.polarity #-1 (negative) a 1 (positive)
print(sentiment)

# Nesse caso temos um texto quase neutro.

# Agora para analisar um texto de autoria própria:

# Aqui pode ser inserido um texto em português e ele será traduzido

with open('mytext.txt', 'r') as f:
  text = f.read()

translation = TextBlob(text)
text = str(translation.translate(from_lang='pt', to='en'))


print(text)

blob = TextBlob(text)
sentiment = blob.sentiment.polarity #-1 (negative) a 1 (positive)
print(sentiment)

if sentiment > 0:
  print('Parece que sua mensagem é bastante positiva')
else:
  print('Parece que sua mensagem tem um caráter negativo!')